"use client";
import { useEffect,useMemo,useState } from "react";
import { CalendarIcon,ShieldIcon } from "./icons";
type Conn={connected:boolean;configured:boolean;providerAccountEmail:string|null;calendarName:string|null;timezone:string|null;lastSyncedAt:string|null;syncStatus:string|null;syncError:string|null};
type Ev={id:string;title:string;location:string|null;startAt:string;endAt:string;localStartDate:string;localEndDate:string;allDay:boolean;attendanceStatus:string;calendarName:string|null};
type Payload={status:"ok";connection:Conn;events:Ev[]};
function d(v:string){return new Intl.DateTimeFormat("pt-BR",{weekday:"short",day:"2-digit",month:"short"}).format(new Date(`${v}T12:00:00`));}
function t(e:Ev){if(e.allDay)return"dia inteiro";const f=new Intl.DateTimeFormat("pt-BR",{hour:"2-digit",minute:"2-digit"});return`${f.format(new Date(e.startAt))}–${f.format(new Date(e.endAt))}`;}
function synced(v:string|null){if(!v)return"ainda não sincronizado";return new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}).format(new Date(v));}
export function RoutineCalendar(){const[payload,setPayload]=useState<Payload|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[notice,setNotice]=useState<string|null>(null);
async function load(){setLoading(true);try{const r=await fetch("/api/pipinho/calendar",{cache:"no-store"}),j=await r.json();if(!r.ok)throw new Error(j?.message??"Calendário indisponível.");setPayload(j);}catch(e){setNotice(e instanceof Error?e.message:"Calendário indisponível.");}finally{setLoading(false);}}
useEffect(()=>{const q=new URLSearchParams(window.location.search),ok=q.get("calendarConnected"),err=q.get("calendarError");if(ok==="1")setNotice("Google Calendar conectado e sincronizado.");if(err)setNotice(err==="oauth_not_configured"?"Configure as variáveis OAuth do Google antes de conectar.":`Não foi possível conectar: ${err}`);if(ok||err)window.history.replaceState({},"","/rotina");void load();},[]);
async function sync(){setBusy(true);try{const r=await fetch("/api/pipinho/calendar/sync",{method:"POST"}),j=await r.json();if(!r.ok)throw new Error(j?.message??"Falha ao sincronizar.");setNotice(`${j.eventCount??0} compromisso(s) sincronizado(s).`);await load();}catch(e){setNotice(e instanceof Error?e.message:"Falha ao sincronizar.");}finally{setBusy(false);}}
async function disconnect(){if(!window.confirm("Desconectar o Google Calendar e apagar os eventos sincronizados?"))return;setBusy(true);try{const r=await fetch("/api/pipinho/calendar",{method:"DELETE"}),j=await r.json();if(!r.ok)throw new Error(j?.message??"Falha ao desconectar.");setNotice("Google Calendar desconectado.");await load();}catch(e){setNotice(e instanceof Error?e.message:"Falha ao desconectar.");}finally{setBusy(false);}}
const groups=useMemo(()=>{const m=new Map<string,Ev[]>();for(const e of payload?.events??[]){const a=m.get(e.localStartDate)??[];a.push(e);m.set(e.localStartDate,a);}return[...m.entries()].sort(([a],[b])=>a.localeCompare(b));},[payload]);const c=payload?.connection;
return <div className="page-stack"><header className="page-header"><div><span className="eyebrow">CICLO 12 · ROTINA</span><h1>Seu calendário vira contexto do Pipinho.</h1><p>Agenda em modo somente leitura, com compromissos, horários e locais disponíveis para o agente.</p></div></header>{notice&&<div className="routine-notice">{notice}</div>}{loading?<section className="panel routine-loading">Carregando rotina…</section>:!c?.connected?<section className="panel routine-connect-panel"><div className="routine-connect-icon"><CalendarIcon/></div><div><span className="eyebrow">GOOGLE CALENDAR</span><h2>Conecte sua agenda.</h2><p>Depois você poderá perguntar “o que tenho amanhã?”, “onde vou depois?” e “quanto gastei no dia da reunião?”.</p>{!c?.configured&&<p className="routine-config-warning">OAuth ainda não configurado. Veja <code>docs/CICLO_12.md</code>.</p>}</div><a className={`routine-primary-button ${!c?.configured?"disabled":""}`} href={c?.configured?"/api/pipinho/calendar/connect":undefined}>Conectar Google Calendar</a></section>:<><section className="routine-connection-strip"><div><span className="eyebrow">CONECTADO</span><strong>{c.calendarName??"Google Calendar"}</strong><small>{c.providerAccountEmail??c.timezone}</small></div><div className="routine-sync-meta"><span>Última sincronização</span><strong>{synced(c.lastSyncedAt)}</strong></div><div className="routine-actions"><button onClick={()=>void sync()} disabled={busy}>{busy?"Sincronizando…":"Sincronizar"}</button><button className="secondary" onClick={()=>void disconnect()} disabled={busy}>Desconectar</button></div></section><section className="panel routine-agenda-panel"><div className="panel-heading"><div><span className="eyebrow">PRÓXIMOS COMPROMISSOS</span><h2>Agenda sincronizada</h2></div><span className="small-pill">{payload?.events.length??0} eventos</span></div>{groups.length===0?<p className="routine-empty">Nenhum compromisso no período sincronizado.</p>:<div className="routine-days">{groups.map(([date,events])=><div className="routine-day" key={date}><div className="routine-day-label">{d(date)}</div><div className="routine-event-list">{events.map(e=><article className="routine-event" key={e.id}><div className="routine-event-time">{t(e)}</div><div className="routine-event-copy"><strong>{e.title}</strong><span>{e.location||"Local não informado"}</span></div>{e.attendanceStatus==="tentative"&&<span className="routine-event-status">talvez</span>}</article>)}</div></div>)}</div>}</section></>}<section className="architecture-note routine-safety-note"><ShieldIcon/><div><span className="eyebrow">FRONTEIRA DE EVIDÊNCIA</span><h2>Evento e gasto no mesmo dia não significam causa.</h2><p>O Pipinho pode combinar a janela temporal de um compromisso com o spending observado, mas deve tratar isso apenas como coincidência temporal.</p></div></section></div>}
