-- Ciclo 11.3 — memória persistente do Pipinho
-- Execute no projeto Supabase usado pelo frontend (SQL Editor ou Supabase CLI).

create table if not exists public.pipinho_chat_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null default 'Nova conversa' check (char_length(title) between 1 and 120),
  routing_memory jsonb not null default '{"version":1,"recentUserQuestions":[]}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.pipinho_chat_messages (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.pipinho_chat_sessions(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('user', 'assistant')),
  content text not null check (char_length(content) between 1 and 12000),
  verified boolean,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists pipinho_chat_sessions_user_updated_idx
  on public.pipinho_chat_sessions(user_id, updated_at desc);

create index if not exists pipinho_chat_messages_session_id_idx
  on public.pipinho_chat_messages(session_id, id desc);

alter table public.pipinho_chat_sessions enable row level security;
alter table public.pipinho_chat_messages enable row level security;

-- Recria as policies para a migration ser reaplicável durante o laboratório.
drop policy if exists "pipinho sessions select own" on public.pipinho_chat_sessions;
drop policy if exists "pipinho sessions insert own" on public.pipinho_chat_sessions;
drop policy if exists "pipinho sessions update own" on public.pipinho_chat_sessions;
drop policy if exists "pipinho sessions delete own" on public.pipinho_chat_sessions;

drop policy if exists "pipinho messages select own" on public.pipinho_chat_messages;
drop policy if exists "pipinho messages insert own" on public.pipinho_chat_messages;
drop policy if exists "pipinho messages delete own" on public.pipinho_chat_messages;

create policy "pipinho sessions select own"
  on public.pipinho_chat_sessions for select
  to authenticated
  using (user_id = auth.uid());

create policy "pipinho sessions insert own"
  on public.pipinho_chat_sessions for insert
  to authenticated
  with check (user_id = auth.uid());

create policy "pipinho sessions update own"
  on public.pipinho_chat_sessions for update
  to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

create policy "pipinho sessions delete own"
  on public.pipinho_chat_sessions for delete
  to authenticated
  using (user_id = auth.uid());

create policy "pipinho messages select own"
  on public.pipinho_chat_messages for select
  to authenticated
  using (
    user_id = auth.uid()
    and exists (
      select 1
      from public.pipinho_chat_sessions session
      where session.id = session_id
        and session.user_id = auth.uid()
    )
  );

create policy "pipinho messages insert own"
  on public.pipinho_chat_messages for insert
  to authenticated
  with check (
    user_id = auth.uid()
    and exists (
      select 1
      from public.pipinho_chat_sessions session
      where session.id = session_id
        and session.user_id = auth.uid()
    )
  );

create policy "pipinho messages delete own"
  on public.pipinho_chat_messages for delete
  to authenticated
  using (
    user_id = auth.uid()
    and exists (
      select 1
      from public.pipinho_chat_sessions session
      where session.id = session_id
        and session.user_id = auth.uid()
    )
  );

revoke all on table public.pipinho_chat_sessions from anon;
revoke all on table public.pipinho_chat_messages from anon;
grant select, insert, update, delete on table public.pipinho_chat_sessions to authenticated;
grant select, insert, delete on table public.pipinho_chat_messages to authenticated;
grant usage, select on sequence public.pipinho_chat_messages_id_seq to authenticated;
